// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sean Brandt

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
)

var multiHyphen = regexp.MustCompile(`-{2,}`)

var docsCmd = &cobra.Command{
	Use:   "docs",
	Short: "Generate CLI reference documentation",
}

var docsCliCmd = &cobra.Command{
	Use:   "cli [output-path]",
	Short: "Generate CLI reference markdown",
	Long:  "Walk the Cobra command tree and generate a grouped CLI reference page.",
	Args:  cobra.MaximumNArgs(1),
	RunE:  runDocsCli,
}

var docsCliDefaultPath = filepath.Join("site", "docs", "cli-reference.md")

func init() {
	docsCmd.AddCommand(docsCliCmd)
	rootCmd.AddCommand(docsCmd)
}

type commandGroup struct {
	Name     string
	Commands []string
}

var commandGroups = []commandGroup{
	{Name: "Spec Management", Commands: []string{"create", "show", "list", "update", "changes"}},
	{Name: "Authoring Funnel", Commands: []string{"spark", "shape", "specify", "decompose", "approve"}},
	{Name: "Slices", Commands: []string{"slice"}},
	{Name: "Graph Queries", Commands: []string{"deps", "impact", "critical-path", "ready", "edge"}},
	{Name: "Drift & Linting", Commands: []string{"drift", "lint"}},
	{Name: "Execution Lifecycle", Commands: []string{"claim", "unclaim", "report-progress", "report-blocker", "report-completion", "bundle", "progress"}},
	{Name: "Lifecycle Transitions", Commands: []string{"amend", "supersede", "abandon"}},
	{Name: "Decisions", Commands: []string{"decision"}},
	{Name: "Constitution", Commands: []string{"constitution"}},
	{Name: "Conversations", Commands: []string{"conversation"}},
	{Name: "Findings", Commands: []string{"findings", "pass"}},
	{Name: "Sync", Commands: []string{"sync"}},
	{Name: "Export & Backup", Commands: []string{"export", "import", "verify"}},
	{Name: "Server & Config", Commands: []string{"up", "down", "install", "uninstall", "serve", "status", "health", "doctor", "init", "prime", "read-mcp-resource"}},
	{Name: "Identity & Auth", Commands: []string{"auth"}},
}

func runDocsCli(_ *cobra.Command, args []string) error {
	outPath := docsCliDefaultPath
	if len(args) > 0 {
		outPath = args[0]
	}

	var sb strings.Builder
	writeHeader(&sb)
	writeTOC(&sb)
	writeGroups(&sb, rootCmd)

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil { //nolint:gosec // docs output dir needs world-read for CI/serve
		return fmt.Errorf("create output dir: %w", err)
	}
	if err := os.WriteFile(outPath, []byte(sb.String()), 0o644); err != nil { //nolint:gosec // committed docs artifact, world-readable
		return fmt.Errorf("write cli reference: %w", err)
	}
	_, _ = fmt.Fprintf(os.Stderr, "CLI reference written to %s\n", outPath)
	return nil
}

func writeHeader(sb *strings.Builder) {
	sb.WriteString("# CLI Reference\n\n")
	sb.WriteString("> Auto-generated by `specgraph docs cli`. Do not edit manually.\n\n")
	sb.WriteString("---\n\n")
}

func writeTOC(sb *strings.Builder) {
	for _, g := range commandGroups {
		anchor := strings.ToLower(g.Name)
		anchor = strings.NewReplacer(" & ", "-", " ", "-").Replace(anchor)
		anchor = multiHyphen.ReplaceAllString(anchor, "-")
		_, _ = fmt.Fprintf(sb, "- [%s](#%s)\n", g.Name, anchor)
	}
	sb.WriteString("\n---\n\n")
}

func writeGroups(sb *strings.Builder, root *cobra.Command) {
	cmdMap := make(map[string]*cobra.Command)
	for _, c := range root.Commands() {
		cmdMap[c.Name()] = c
	}

	written := make(map[string]bool)
	for _, g := range commandGroups {
		_, _ = fmt.Fprintf(sb, "## %s\n\n", g.Name)
		for _, name := range g.Commands {
			cmd, ok := cmdMap[name]
			if !ok {
				continue
			}
			writeCommand(sb, cmd, "###")
			written[name] = true
		}
	}

	var other []*cobra.Command
	for _, c := range root.Commands() {
		if !written[c.Name()] && c.Name() != "help" && c.Name() != "completion" && c.Name() != "docs" {
			other = append(other, c)
		}
	}
	if len(other) > 0 {
		sb.WriteString("## Other\n\n")
		for _, c := range other {
			writeCommand(sb, c, "###")
		}
	}
}

func writeCommand(sb *strings.Builder, cmd *cobra.Command, heading string) {
	_, _ = fmt.Fprintf(sb, "%s %s\n\n", heading, cmd.CommandPath())

	if cmd.Long != "" {
		sb.WriteString(cmd.Long + "\n\n")
	} else if cmd.Short != "" {
		sb.WriteString(cmd.Short + "\n\n")
	}

	_, _ = fmt.Fprintf(sb, "```\n%s\n```\n\n", cmd.UseLine())

	if cmd.HasAvailableLocalFlags() {
		sb.WriteString("**Flags:**\n\n```\n")
		sb.WriteString(cmd.LocalFlags().FlagUsages())
		sb.WriteString("```\n\n")
	}

	if cmd.Example != "" {
		sb.WriteString("**Examples:**\n\n```bash\n")
		sb.WriteString(cmd.Example)
		sb.WriteString("\n```\n\n")
	}

	for _, sub := range cmd.Commands() {
		if sub.Name() == "help" {
			continue
		}
		writeCommand(sb, sub, heading+"#")
	}
}
