// SPDX-License-Identifier: MIT
// Copyright 2026 Sean Brandt

// Package emitter converts constitutions into tool-specific configuration files.
package emitter

import (
	"fmt"
	"strings"

	specv1 "github.com/seanb4t/specgraph/gen/specgraph/v1"
)

// Emit generates a tool-specific file from the given constitution.
// Supported formats: "claude-md", "cursorrules", "agents-md".
func Emit(c *specv1.Constitution, format string) (content, filename string, err error) {
	switch format {
	case "claude-md":
		return emitClaudeMD(c), "CLAUDE.md", nil
	case "cursorrules":
		return emitCursorrules(c), ".cursorrules", nil
	case "agents-md":
		return emitAgentsMD(c), "AGENTS.md", nil
	default:
		return "", "", fmt.Errorf("unsupported format: %s", format)
	}
}

func emitClaudeMD(c *specv1.Constitution) string {
	var b strings.Builder

	b.WriteString("# Project Constitution\n\n")
	b.WriteString("Generated by SpecGraph. Do not edit manually.\n\n")

	writeTechSection(&b, c)
	writePrinciplesSection(&b, c)
	writeConstraintsSection(&b, c)
	writeAntipatternSection(&b, c)

	return b.String()
}

func emitCursorrules(c *specv1.Constitution) string {
	var b strings.Builder

	b.WriteString("# Project Rules (Generated by SpecGraph)\n\n")

	writeTechSection(&b, c)
	writePrinciplesSection(&b, c)
	writeConstraintsSection(&b, c)
	writeAntipatternSection(&b, c)

	return b.String()
}

func emitAgentsMD(c *specv1.Constitution) string {
	var b strings.Builder

	b.WriteString("# Agent Instructions\n\n")
	b.WriteString("Generated by SpecGraph. Do not edit manually.\n\n")

	writeTechSection(&b, c)
	writePrinciplesSection(&b, c)
	writeConstraintsSection(&b, c)
	writeAntipatternSection(&b, c)

	return b.String()
}

func writeTechSection(b *strings.Builder, c *specv1.Constitution) {
	if c.Tech == nil {
		return
	}

	b.WriteString("## Tech Stack\n\n")

	if c.Tech.Languages != nil {
		fmt.Fprintf(b, "- **Primary language:** %s\n", c.Tech.Languages.Primary)
		if len(c.Tech.Languages.Allowed) > 0 {
			fmt.Fprintf(b, "- **Allowed languages:** %s\n", strings.Join(c.Tech.Languages.Allowed, ", "))
		}
		if len(c.Tech.Languages.Forbidden) > 0 {
			fmt.Fprintf(b, "- **Forbidden languages:** %s\n", strings.Join(c.Tech.Languages.Forbidden, ", "))
			for lang, reason := range c.Tech.Languages.ForbiddenReasons {
				fmt.Fprintf(b, "  - %s: %s\n", lang, reason)
			}
		}
	}

	if len(c.Tech.Frameworks) > 0 {
		b.WriteString("\n**Frameworks:**\n\n")
		for area, framework := range c.Tech.Frameworks {
			fmt.Fprintf(b, "- %s: %s\n", area, framework)
		}
	}

	if len(c.Tech.Infrastructure) > 0 {
		b.WriteString("\n**Infrastructure:**\n\n")
		for area, tech := range c.Tech.Infrastructure {
			fmt.Fprintf(b, "- %s: %s\n", area, tech)
		}
	}

	b.WriteString("\n")
}

func writePrinciplesSection(b *strings.Builder, c *specv1.Constitution) {
	if len(c.Principles) == 0 {
		return
	}

	b.WriteString("## Principles\n\n")
	for _, p := range c.Principles {
		fmt.Fprintf(b, "- **%s**: %s", p.Id, p.Principle)
		if p.Rationale != "" {
			fmt.Fprintf(b, " (%s)", p.Rationale)
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

func writeConstraintsSection(b *strings.Builder, c *specv1.Constitution) {
	if len(c.Constraints) == 0 {
		return
	}

	b.WriteString("## Constraints\n\n")
	for _, constraint := range c.Constraints {
		fmt.Fprintf(b, "- %s\n", constraint)
	}
	b.WriteString("\n")
}

func writeAntipatternSection(b *strings.Builder, c *specv1.Constitution) {
	if len(c.Antipatterns) == 0 {
		return
	}

	b.WriteString("## Anti-patterns\n\n")
	for _, ap := range c.Antipatterns {
		fmt.Fprintf(b, "- **%s**", ap.Pattern)
		if ap.Why != "" {
			fmt.Fprintf(b, " — %s", ap.Why)
		}
		if ap.Instead != "" {
			fmt.Fprintf(b, ". Instead: %s", ap.Instead)
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}
