// SPDX-License-Identifier: MIT
// Copyright 2026 Sean Brandt

package auth

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/specgraph/specgraph/internal/config"
)

// CredentialsFile is the structure of the credentials.yaml file.
type CredentialsFile struct {
	APIKeys []config.APIKeyConfig `yaml:"api_keys"`
}

// Bootstrap generates a default admin API key and writes it to credentialsPath.
// If the file already exists, reads and returns the existing key.
// Returns the generated/existing API key value.
func Bootstrap(credentialsPath string) (string, error) {
	// Check if file already exists.
	data, err := os.ReadFile(credentialsPath)
	if err == nil {
		var creds CredentialsFile
		if unmarshalErr := yaml.Unmarshal(data, &creds); unmarshalErr != nil {
			return "", fmt.Errorf("parse existing credentials: %w", unmarshalErr)
		}
		if len(creds.APIKeys) > 0 {
			return creds.APIKeys[0].Key, nil
		}
	} else if !errors.Is(err, fs.ErrNotExist) {
		return "", fmt.Errorf("read credentials: %w", err)
	}

	// Generate new key.
	keyBytes := make([]byte, 16)
	if _, err := rand.Read(keyBytes); err != nil {
		return "", fmt.Errorf("generate random key: %w", err)
	}
	key := "spgr_sk_" + hex.EncodeToString(keyBytes)

	creds := CredentialsFile{
		APIKeys: []config.APIKeyConfig{
			{
				ID:   "default-admin",
				Key:  key,
				Name: "Default Admin (auto-generated)",
				Role: "admin",
			},
		},
	}

	yamlData, err := yaml.Marshal(creds)
	if err != nil {
		return "", fmt.Errorf("marshal credentials: %w", err)
	}

	header := []byte("# Auto-generated by specgraph server bootstrap. Do not commit to version control.\n")
	content := append(header, yamlData...)

	if err := os.MkdirAll(filepath.Dir(credentialsPath), 0o750); err != nil {
		return "", fmt.Errorf("create credentials directory: %w", err)
	}

	if err := os.WriteFile(credentialsPath, content, 0o600); err != nil {
		return "", fmt.Errorf("write credentials: %w", err)
	}

	return key, nil
}

// CheckCredentialPermissions returns a warning message if the credentials file
// has permissions more open than 0600. Returns "" if permissions are OK or
// the file doesn't exist.
func CheckCredentialPermissions(path string) string {
	info, err := os.Stat(path)
	if err != nil {
		return ""
	}
	perm := info.Mode().Perm()
	if perm != 0o600 {
		return fmt.Sprintf("credentials file %s has permissions %04o (expected 0600)", path, perm)
	}
	return ""
}
