// SPDX-License-Identifier: MIT
// Copyright 2026 Sean Brandt

package auth

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/specgraph/specgraph/internal/config"
)

// CredentialsFile is the structure of the credentials.yaml file.
type CredentialsFile struct {
	APIKeys []config.APIKeyConfig `yaml:"api_keys"`
}

// Bootstrap generates a default admin API key and writes it to credentialsPath.
// If the file already exists, reads and returns the existing key.
// Uses O_CREATE|O_EXCL for atomic creation to avoid TOCTOU races.
// Returns the generated/existing API key value.
func Bootstrap(credentialsPath string) (string, error) {
	if err := os.MkdirAll(filepath.Dir(credentialsPath), 0o750); err != nil {
		return "", fmt.Errorf("create credentials directory: %w", err)
	}

	// Generate new key.
	keyBytes := make([]byte, 16)
	if _, randErr := rand.Read(keyBytes); randErr != nil {
		return "", fmt.Errorf("generate random key: %w", randErr)
	}
	key := "spgr_sk_" + hex.EncodeToString(keyBytes)

	creds := CredentialsFile{
		APIKeys: []config.APIKeyConfig{
			{
				ID:   "default-admin",
				Key:  key,
				Name: "Default Admin (auto-generated)",
				Role: "admin",
			},
		},
	}

	yamlData, err := yaml.Marshal(creds)
	if err != nil {
		return "", fmt.Errorf("marshal credentials: %w", err)
	}

	header := "# Auto-generated by specgraph server bootstrap. Do not commit to version control.\n"
	content := append([]byte(header), yamlData...)

	// Atomic exclusive create — if file already exists, read the existing key.
	if err := writeNewCredentials(credentialsPath, content); err != nil {
		if errors.Is(err, fs.ErrExist) {
			return readExistingBootstrapKey(credentialsPath)
		}
		return "", err
	}

	return key, nil
}

// writeNewCredentials atomically creates the credentials file using O_EXCL.
// Returns fs.ErrExist if the file already exists.
func writeNewCredentials(path string, content []byte) (err error) {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return fmt.Errorf("create credentials: %w", err)
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil && err == nil {
			err = fmt.Errorf("close credentials: %w", closeErr)
		}
	}()

	if _, err := f.Write(content); err != nil {
		return fmt.Errorf("write credentials: %w", err)
	}
	return nil
}

// readExistingBootstrapKey reads the first API key from an existing credentials file.
func readExistingBootstrapKey(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read existing credentials: %w", err)
	}
	var creds CredentialsFile
	if err := yaml.Unmarshal(data, &creds); err != nil {
		return "", fmt.Errorf("parse existing credentials: %w", err)
	}
	if len(creds.APIKeys) == 0 {
		return "", fmt.Errorf("credentials file exists but contains no API keys")
	}
	return creds.APIKeys[0].Key, nil
}

// CheckCredentialPermissions returns a warning message if the credentials file
// has permissions more open than 0600. Returns "" if permissions are OK or
// the file doesn't exist.
func CheckCredentialPermissions(path string) string {
	info, err := os.Stat(path)
	if err != nil {
		return ""
	}
	perm := info.Mode().Perm()
	if perm&^0o600 != 0 { // warn only if group/other bits are set (more permissive than 0600)
		return fmt.Sprintf("credentials file %s has permissions %04o (expected 0600 or stricter)", path, perm)
	}
	return ""
}
